<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" total="8" passed="6">
  <reporter-output>
  </reporter-output>
  <suite name="Default Suite" duration-ms="171634" started-at="2019-02-28T09:04:12Z" finished-at="2019-02-28T09:07:04Z">
    <groups>
    </groups>
    <test name="game" duration-ms="171634" started-at="2019-02-28T09:04:12Z" finished-at="2019-02-28T09:07:04Z">
      <class name="InbetAdminTestCase.AdminHomeTest">
        <test-method status="PASS" signature="serviceFeeIncome()[pri:1, instance:InbetAdminTestCase.AdminHomeTest@338d47b]" name="serviceFeeIncome" duration-ms="25397" started-at="2019-02-28T16:04:12Z" finished-at="2019-02-28T16:04:37Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- serviceFeeIncome -->
        <test-method status="PASS" signature="sinceBusinessOperationsTotalArrears()[pri:2, instance:InbetAdminTestCase.AdminHomeTest@338d47b]" name="sinceBusinessOperationsTotalArrears" duration-ms="23638" started-at="2019-02-28T16:04:38Z" finished-at="2019-02-28T16:05:01Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sinceBusinessOperationsTotalArrears -->
        <test-method status="PASS" signature="busniessMoneyTotal()[pri:3, instance:InbetAdminTestCase.AdminHomeTest@338d47b]" name="busniessMoneyTotal" duration-ms="21274" started-at="2019-02-28T16:05:01Z" finished-at="2019-02-28T16:05:23Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- busniessMoneyTotal -->
        <test-method status="PASS" signature="playerNumber()[pri:4, instance:InbetAdminTestCase.AdminHomeTest@338d47b]" name="playerNumber" duration-ms="19525" started-at="2019-02-28T16:05:23Z" finished-at="2019-02-28T16:05:42Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- playerNumber -->
        <test-method status="FAIL" signature="systermWinOrLose()[pri:5, instance:InbetAdminTestCase.AdminHomeTest@338d47b]" name="systermWinOrLose" duration-ms="18061" started-at="2019-02-28T16:05:42Z" finished-at="2019-02-28T16:06:00Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at InbetAdminTestCase.AdminHomeTest.systermWinOrLose(AdminHomeTest.java:156)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1191)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)
	at org.testng.TestNG.run(TestNG.java:1024)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- systermWinOrLose -->
        <test-method status="FAIL" signature="totalsystermWinOrLose()[pri:6, instance:InbetAdminTestCase.AdminHomeTest@338d47b]" name="totalsystermWinOrLose" duration-ms="22797" started-at="2019-02-28T16:06:00Z" finished-at="2019-02-28T16:06:23Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at InbetAdminTestCase.AdminHomeTest.totalsystermWinOrLose(AdminHomeTest.java:186)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1191)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)
	at org.testng.TestNG.run(TestNG.java:1024)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- totalsystermWinOrLose -->
        <test-method status="PASS" signature="todayCommission()[pri:7, instance:InbetAdminTestCase.AdminHomeTest@338d47b]" name="todayCommission" duration-ms="20880" started-at="2019-02-28T16:06:23Z" finished-at="2019-02-28T16:06:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- todayCommission -->
        <test-method status="PASS" signature="totalCommission()[pri:8, instance:InbetAdminTestCase.AdminHomeTest@338d47b]" name="totalCommission" duration-ms="19872" started-at="2019-02-28T16:06:44Z" finished-at="2019-02-28T16:07:04Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- totalCommission -->
      </class> <!-- InbetAdminTestCase.AdminHomeTest -->
    </test> <!-- game -->
  </suite> <!-- Default Suite -->
</testng-results>
